/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #            newlib heap             #     .out         #
 * #         #        #                                    # (DMA buffers)    #
 * ############################################################################
 * ^-- RAM start      ^-- _end             __HeapLimit --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '__HeapLimit' linker symbol (defined in the linker script) bounds the
 * heap. On the flash build _estack points into CCM RAM, which is above/below
 * the SRAM addresses and therefore useless as a heap bound, so the bound is
 * set explicitly to the start of the .out region (DMA audio buffers).
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint32_t __HeapLimit; /* Symbol defined in the linker script */
  const uint8_t *max_heap = (const uint8_t *)&__HeapLimit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* Protect heap from growing into the reserved regions (.out, stack) */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

/**
 * @brief  Возвращает количество свободных байт newlib-кучи
 * @retval свободно байт (0, если куча достигла __HeapLimit)
 */
uint32_t get_newlib_heap_free(void)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint32_t __HeapLimit; /* Symbol defined in the linker script */
  const uint8_t *heap_end = (__sbrk_heap_end != NULL) ? __sbrk_heap_end : &_end;
  const uint8_t *limit = (const uint8_t *)&__HeapLimit;
  return (heap_end < limit) ? (uint32_t)(limit - heap_end) : 0;
}
